### PR TITLE
NES Mapper 19 synchronized

### PR DESCRIPTION
**Pull request by Raulie**
Needed for Pac-Man CE 2020

### CODE REVIEW

**Comment by kbeckmann** [comment]
Thanks! This is more or less the current state in the upstream project, right? Have we diverged so much that we can't use their files without changes anymore?

This line seems to be a bit different upstream https://github.com/ducalex/retro-go/blob/master/nofrendo-go/components/nofrendo/mappers/map019.c#L135 and there are some calls to nes6502_irq_clear(). Not sure what that affects as I basically have no idea how the emulator works (I've just integrated it and made it work on the G&W).

**Comment by Raulie** [comment]
That's right, we can't use the current one. Our version has a TODO in mapper 19 that was later implemented with this commit:

https://github.com/ducalex/retro-go/commit/910538ce5179b1816d972233e663dc2eb15929e3#diff-72d6943be7850e8b6e4e3143c89c769ed39d34dd832b0192204dec63b9b580b5

I just included those changes, which make the game work.

**Comment by kbeckmann** [comment]
Cool, then I understand.

**Comment by kbeckmann** [comment]
Oops, merged into the wrong branch. It's supposed to go into the branch called nintendogw-main2

**Pull request merged**
